### ISSUE TITLE
dig not listed as dependency

### ISSUE THREAD

**Issue by gbl08ma** [yinguanhao/acme-dns-hook-cloudflare#1]
dig should be listed as dependency. It'd be even better if the use of dig could be avoided, as it's not available on all systems and it's not trivial to install on certain Linux distros (like Debian), because it is not on the default repositories.

Edit: it looks like dig is in the dnsutils package, but still, it would be good to have it listed as dependency. Alternatively, you can use a Python library like dnspython or pydns in place of dig.

**Comment by blckngm** [comment]
I think `dig` is widely available, and `dnspython` looks too complex, so I will just list `dig` as a dependency.

It's nice to know that this small program might be helpful to others though, thanks for the feedback.
